version: "3"
services:
  ngnix-dns-reg-{version}:
    environment:
    - REDISSERVER=redis
    - REDISPORT=6379
    ports:
    - "9099:8080"
    container_name: ngnix-dns-reg-{version}
    volumes:
    - 'ngnix:/etc/nginx-config/config/sites'
    - 'templates:/etc/nginx-config/config/template'
    build:
      context: .
      dockerfile: ../Dockerfile
    image: 192.168.233.1:5000/ngnix-dns-reg:{version}
    networks:
    - dev
  ngnix-{version}:
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - 'ngnix:/etc/nginx/sites-enabled'
    - 'certs:/etc/nginx/certs'
    container_name: ngnix-server-{version}
    image: arm32v7/nginx
    networks:
    - dev
volumes:
  ngnix:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.233.1,nolock,soft,rw"
      device: ":/docker/nginx/sites"
  templates:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.233.1,nolock,soft,rw"
      device: ":/docker/nginx/templates"
  certs:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.233.1,nolock,soft,rw"
      device: ":/docker/nginx/certs"
networks:
  dev:
    external:
      name: dev