version: "3"
services:
  ngnix-dns-reg-{version}:
    environment:
    - REDISSERVER=redis
    - REDISPORT=6379
    ports:
    - "9099:8080"
    volumes:
    - 'sites:/etc/nginx-config/config/sites'
    - 'templates:/etc/nginx-config/config/template'
    build:
      context: .
      dockerfile: ../Dockerfile
    image: 192.168.233.1:5000/ngnix-dns-reg:{version}
    networks:
      dev:
        aliases:
        - ngnix-dns-reg-{version}
volumes:
  sites:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.233.1,nolock,soft,rw"
      device: ":/docker/nginx/sites"
  templates:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.233.1,nolock,soft,rw"
      device: ":/docker/nginx/templates"
networks:
  dev:
    external:
      name: dev