version: "3"
services:
  app:
    environment:
    - MONGOSERVER=nxdrmongodb
    - MONGOPORT=27017
    ports:
    - "80:80"
    - "443:443"
    - "9099:8080"
    volumes:
    - 'certs:/etc/nginx/certs'
    - 'templates:/etc/nginx-config/config/template'
    build:
      context: .
      dockerfile: ../Dockerfile
    image: {image}
    networks:
      dev:
        aliases:
         - {alias}
volumes:
  templates:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.233.1,nolock,soft,rw"
      device: ":/docker/nginx/templates"
  certs:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.233.1,nolock,soft,rw"
      device: ":/docker/nginx/certs"

networks:
  dev:
    external:
      name: dev
