version: "3"
services:
  pipeline-example-{version}:
    environment:
    - REDISSERVER=redis
    - REDISPORT=6379
    ports:
    - "9099:8080"
    container_name: ngnix-dns-reg-{version}
    build:
      context: .
      dockerfile: ../Dockerfile
    image: 192.168.233.1:5000/ngnix-dns-reg:{version}
