spring:
  profiles: default
  data:
    mongodb:
      host: localhost
      port: 27017
      repositories:
        enabled: true
      database: nxdr
cors:
  allowedOrigins: '*'
  allowedHeaders:
    - Authorization
    - Content-Type
  exposedHeaders:
    - Authorization
    - Content-Type
template:
   sites-path: /home/sascha/dev/github/nginx-dns-reg/target/
   template-path: /home/sascha/dev/github/nginx-dns-reg/src/main/resources/templates
   certsPath: /home/sascha

---
spring:
  profiles: docker
  data:
    mongodb:
      host: ${MONGOSERVER}
      port: ${MONGOPORT}
      repositories:
        enabled: true
      database: nxdr
cors:
  allowedOrigins: '*'
  allowedHeaders:
    - Authorization
    - Content-Type
  exposedHeaders:
    - Authorization
    - Content-Type
template:
  sitesPath: /etc/nginx/conf.d/
  templatePath: /etc/nginx-config/config/template
  certsPath: /etc/nginx/certs